
version: "3"

services:
    nodered:
        container_name: node-red
        ports:
            - '1880:1880'
        volumes:
            - 'nodered:/data'
        environment:
            - NODE_OPTIONS=--max_old_space_size=128
        image: nodered/node-red
        networks:
            - ops
    
    influxdb:
        container_name: influxdb
        image: "influxdb"
        networks:
          - ops
        ports:
          - "8086:8086"
        volumes:
          - influxdb:/var/lib/influxdb 
        environment:
          - INFLUXDB_DB=remnetmon
          - INFLUXDB_USER=remmonadmin
          - INFLUXDB_ADMIN_ENABLED=true
          - INFLUXDB_ADMIN_USER=admin
          - INFLUXDB_ADMIN_PASSWORD=g00gler0x 
        restart: on-failure
        
    grafana:
        container_name: grafana
        image: "grafana/grafana"
        networks:
          - ops
        ports:
          - "3000:3000"
        volumes:
          - grafana:/var/lib/grafana
        environment:
          - GF_INSTALL_PLUGINS=grafana-clock-panel,natel-discrete-panel,briangann-gauge-panel,vonage-status-panel,neocat-cal-heatmap-panel
        restart: on-failure

volumes:
  nodered:
  influxdb:
  grafana:

networks:
  ops:
  management:
  